extends: '@waiting/eslint-config/recommended'
parserOptions:
  project: 'tsconfig.eslint.json'

rules:
  "@typescript-eslint/prefer-ts-expect-error": 0
  "import/no-extraneous-dependencies":
    - 2
    - packageDir:
      - ./
      - ../../node_modules/@mwcp/share/


