extends: '@waiting/eslint-config/recommended'
parserOptions:
  project: 'tsconfig.eslint.json'

rules:
  "@typescript-eslint/no-unused-vars": 0
  "node/no-unpublished-import": 0
  "@typescript-eslint/prefer-ts-expect-error": 0
  "unicorn/filename-case": 0
  "import/no-extraneous-dependencies": 0

